using Horizon.Atmosphere;
using Horizon.World;
using UnityEngine;

namespace Horizon.Game
{
    /// <summary>
    /// How much world to draw, in three settings.
    ///
    /// <para><b>What this deliberately does not touch: the URP assets.</b>
    /// <c>Assets/Settings/Mobile_RPAsset.asset</c> holds the render scale, the MSAA count and the shadow
    /// distance, and it would be the obvious place to put a quality slider. It is also not generated by
    /// <c>PrototypeSetup</c>, and Unity does <b>not</b> roll asset changes back when Play mode ends — so
    /// a player who tried Low once would leave that file modified in the working tree, which is the same
    /// hazard <c>TownLights</c> documents for materials. <c>QualitySettings.SetQualityLevel</c> is no way
    /// round it either: there are exactly two levels, Mobile and PC, each excluded from the other's
    /// platform. Everything here is therefore a runtime value on a component.</para>
    ///
    /// <para>Worth knowing while reading this: URP ignores <c>QualitySettings.shadowDistance</c> and
    /// <c>shadowCascades</c> entirely — it has its own — so setting them would look like it worked and
    /// do nothing. Shadows are switched at the source instead, through
    /// <see cref="TimeOfDayController.Shadows"/>.</para>
    ///
    /// <para><b>Two phases, because the world arrives late.</b> <see cref="Apply"/> handles what is
    /// global and can be set before anything exists — the frame rate. <see cref="ApplyToWorld"/> handles
    /// the streamer, the traffic and the sun, and can only run once the additive load has finished.</para>
    /// </summary>
    public sealed class QualityDirector : MonoBehaviour
    {
        /// <summary>One setting, as the numbers it actually moves.</summary>
        [System.Serializable]
        public struct Level
        {
            public string Name;

            [Header("World streaming")]
            public float StreamLoadRadius;
            public float StreamUnloadRadius;
            public float StreamPhysicsMargin;

            [Header("Traffic")]
            [Tooltip("How many of the 96 pooled cars are simulated and drawn.")]
            public int TrafficBudget;

            public float TrafficLoadRadius;
            public float TrafficRecycleRadius;

            [Header("Rendering")]
            public bool SunShadows;

            [Tooltip("Exhaust smoke and flames. Two particle systems, and the only ones on the car.")]
            public bool ExhaustParticles;

            [Tooltip("30 on Low is a real thermal and battery win on a weak phone, and a steady 30 "
                   + "reads better than a 60 that cannot hold.")]
            public int TargetFrameRate;
        }

        [SerializeField] private Level[] levels = new Level[0];

        /// <summary>The setting currently applied.</summary>
        public QualityPreset Current { get; private set; } = QualityPreset.Balanced;

        /// <summary>The level record for a preset, clamped to what was actually baked.</summary>
        public Level LevelFor(QualityPreset preset)
        {
            if (levels == null || levels.Length == 0)
            {
                return default;
            }

            return levels[Mathf.Clamp((int)preset, 0, levels.Length - 1)];
        }

        /// <summary>
        /// Applies what can be set before the world exists. Called from <c>GameBootstrap.Awake</c>,
        /// which is the last moment before the additive load starts.
        /// </summary>
        public void Apply(QualityPreset preset)
        {
            Current = preset;

            Level level = LevelFor(preset);
            if (level.TargetFrameRate > 0)
            {
                Application.targetFrameRate = level.TargetFrameRate;
            }
        }

        /// <summary>
        /// Applies the world-scoped half: streaming radii, traffic budget, sun shadows and the car's
        /// exhaust emitters.
        ///
        /// <para>Called twice, on purpose. <c>WorldStreamingDriver</c> asks for it before its own first
        /// streaming pass — that pass is deliberately immediate, "or the first few frames render every
        /// chunk in the world", and it is not ordered against <c>GameBootstrap</c>'s resumed coroutine.
        /// <c>StartScreen</c> then calls it again once everything is wired. Both are cheap and both are
        /// idempotent; relying on either one alone is relying on a race.</para>
        /// </summary>
        public void ApplyToWorld()
        {
            Level level = LevelFor(Current);
            if (string.IsNullOrEmpty(level.Name))
            {
                return;
            }

            WorldStreamer streamer = FindFirstObjectByType<WorldStreamer>();
            if (streamer != null)
            {
                streamer.SetRadii(
                    level.StreamLoadRadius, level.StreamUnloadRadius, level.StreamPhysicsMargin);
            }

            TrafficDirector traffic = FindFirstObjectByType<TrafficDirector>();
            if (traffic != null)
            {
                traffic.SetRanges(level.TrafficLoadRadius, level.TrafficRecycleRadius);
                traffic.ActiveBudget = level.TrafficBudget;
            }

            TimeOfDayController timeOfDay = FindFirstObjectByType<TimeOfDayController>();
            if (timeOfDay != null && timeOfDay.Shadows != level.SunShadows)
            {
                timeOfDay.Shadows = level.SunShadows;
                timeOfDay.Apply();
            }

            SetExhaustEnabled(level.ExhaustParticles);
        }

        /// <summary>
        /// Switches the car's two tailpipe emitters on or off.
        ///
        /// <para>Found through the vehicle rather than cached, because the car's active body — and
        /// therefore which pair of emitters exists — changes whenever the player picks another shape.
        /// A cached reference would be to the emitters of a car nobody is driving. This runs on a
        /// settings change, not per frame, so the search costs nothing that matters.</para>
        /// </summary>
        private static void SetExhaustEnabled(bool enabled)
        {
            Vehicle.VehicleController vehicle = FindFirstObjectByType<Vehicle.VehicleController>();
            if (vehicle == null)
            {
                return;
            }

            Vehicle.ExhaustSmoke[] emitters = vehicle.GetComponentsInChildren<Vehicle.ExhaustSmoke>(true);
            for (int i = 0; i < emitters.Length; i++)
            {
                emitters[i].enabled = enabled;

                var particles = emitters[i].GetComponent<ParticleSystem>();
                if (particles == null)
                {
                    continue;
                }

                if (enabled)
                {
                    particles.Play();
                }
                else
                {
                    // Clear as well as stop, or the plume that was in the air hangs there.
                    particles.Stop(true, ParticleSystemStopBehavior.StopEmittingAndClear);
                }
            }
        }
    }
}
