using Horizon.Atmosphere;
using Horizon.World;
using UnityEngine;
using UnityEngine.Rendering.Universal;

namespace Horizon.Game
{
    /// <summary>
    /// How much world to draw, in three settings.
    ///
    /// <para><b>What this deliberately does not touch: the URP assets.</b>
    /// <c>Assets/Settings/Mobile_RPAsset.asset</c> holds the render scale, the MSAA count and the shadow
    /// distance, and it would be the obvious place to put a quality slider. It is also not generated by
    /// <c>PrototypeSetup</c>, and Unity does <b>not</b> roll asset changes back when Play mode ends — so
    /// a player who tried Low once would leave that file modified in the working tree, which is the same
    /// hazard <c>TownLights</c> documents for materials. <c>QualitySettings.SetQualityLevel</c> is no way
    /// round it either: there are exactly two levels, Mobile and PC, each excluded from the other's
    /// platform. Everything here is therefore a runtime value on a component.</para>
    ///
    /// <para>Worth knowing while reading this: URP ignores <c>QualitySettings.shadowDistance</c> and
    /// <c>shadowCascades</c> entirely — it has its own — so setting them would look like it worked and
    /// do nothing. Shadows are switched at the source instead, through
    /// <see cref="TimeOfDayController.Shadows"/>.</para>
    ///
    /// <para><b>Which is also why the shadow distance is not a level here, and does not need to be.</b>
    /// It went from 50 m to 130 on the mobile asset, against a 600 m far plane and roughly 700 m of
    /// visibility at noon — the whole middle distance of every frame was unshadowed and therefore flat.
    /// That is a committed edit to <c>Mobile_RPAsset</c> rather than a runtime write, because a runtime
    /// write is exactly the hazard the paragraph above describes. Staging it per preset would need one
    /// anyway, and there is nothing to stage: Low has <see cref="Level.SunShadows"/> off, so a shadow
    /// distance means nothing there, and Balanced and High both want the reach. The distance is free —
    /// the cascade count stays at 1 and the map stays at 1024, so it is one wider orthographic
    /// projection and not one extra pass. It costs texel density: 4.9 cm per texel became 12.7 cm, which
    /// on a world whose smallest object is a 0.32 m sign post is still finer than the geometry.</para>
    ///
    /// <para><b>Two phases, because the world arrives late.</b> <see cref="Apply"/> handles what is
    /// global and can be set before anything exists — the frame rate. <see cref="ApplyToWorld"/> handles
    /// the streamer, the traffic and the sun, and can only run once the additive load has finished.</para>
    /// </summary>
    public sealed class QualityDirector : MonoBehaviour
    {
        /// <summary>One setting, as the numbers it actually moves.</summary>
        [System.Serializable]
        public struct Level
        {
            public string Name;

            [Header("World streaming")]
            public float StreamLoadRadius;
            public float StreamUnloadRadius;
            public float StreamPhysicsMargin;

            [Header("Traffic")]
            [Tooltip("How many of the 96 pooled cars are simulated and drawn.")]
            public int TrafficBudget;

            public float TrafficLoadRadius;
            public float TrafficRecycleRadius;

            [Header("Rendering")]
            public bool SunShadows;

            [Tooltip("Whether the camera runs FXAA.\n\n"
                   + "The world is flat-shaded, untextured and made almost entirely of hard silhouette "
                   + "edges, and it is rendered at RenderScale 0.8 — which is the worst case there is "
                   + "for edge crawl. It had no antialiasing of any kind until this field existed: both "
                   + "pipeline assets carry MSAA 1 while a comment on the camera claimed MSAA was "
                   + "handling it.\n\n"
                   + "A camera setting rather than the asset's MSAA, for the reason the budget note "
                   + "already gives: 2x on a tile GPU halves the tile and doubles the bins in a world "
                   + "that is geometry-bound, and it would be antialiasing an image that is about to be "
                   + "upscaled. FXAA is a fixed cost on the resolved buffer after the upscale, which is "
                   + "why it is the one that can be afforded at all — and still not on Low, where the "
                   + "sun casts no shadows either and the frame is already the cheapest thing the "
                   + "project can draw.")]
            public bool CameraAntialiasing;

            [Tooltip("Exhaust smoke and flames. Two particle systems on the active body.")]
            public bool ExhaustParticles;

            [Tooltip("Smoke off the tyres when they slide.\n\n"
                   + "Kept apart from the exhaust rather than folded in with it, because the two cost "
                   + "very different things. The tailpipes trickle at a fixed low rate all the time; "
                   + "this one is idle for most of a drive and then asks for its whole budget at once, "
                   + "during a slide — which is also the frame that is already doing the most work.")]
            public bool TyreSmokeParticles;

            [Tooltip("The grit hanging in the air at speed.\n\n"
                   + "The first thing to go on a weak phone, and the easiest call of the three: it is "
                   + "pure atmosphere, it is only ever on show while the player is going fast, and the "
                   + "fog closing in — which costs nothing at all — carries the same message without it.")]
            public bool AirRushParticles;

            [Tooltip("How many raindrops of the full count to draw, 0 to 1.\n\n"
                   + "A fraction rather than a switch, because rain is the one weather effect that has "
                   + "to be visible at all if it is chosen at all — a Low phone showing no rain while "
                   + "the sound falls and the road is slippery is a bug, not a saving. The sky, the "
                   + "noise and the grip never scale with this; only the drop count does.")]
            public float RainDrops;

            [Tooltip("How much of the bloom volume to blend in, 0 to 1.\n\n"
                   + "The tone map and the colour grade are never scaled — they are what the world's "
                   + "colour is, and a phone that skipped them would be showing different art rather "
                   + "than cheaper art. Bloom is the separable half: it is one extra blur chain on the "
                   + "colour buffer, it is the most expensive thing in the stack on a tile GPU, and "
                   + "without it a bright lamp is merely a bright lamp rather than a bad one.")]
            public float Bloom;

            [Tooltip("30 on Low is a real thermal and battery win on a weak phone, and a steady 30 "
                   + "reads better than a 60 that cannot hold.")]
            public int TargetFrameRate;
        }

        [SerializeField] private Level[] levels = new Level[0];

        /// <summary>The setting currently applied.</summary>
        public QualityPreset Current { get; private set; } = QualityPreset.Balanced;

        /// <summary>The level record for a preset, clamped to what was actually baked.</summary>
        public Level LevelFor(QualityPreset preset)
        {
            if (levels == null || levels.Length == 0)
            {
                return default;
            }

            return levels[Mathf.Clamp((int)preset, 0, levels.Length - 1)];
        }

        /// <summary>
        /// Applies what can be set before the world exists. Called from <c>GameBootstrap.Awake</c>,
        /// which is the last moment before the additive load starts.
        /// </summary>
        public void Apply(QualityPreset preset)
        {
            Current = preset;

            Level level = LevelFor(preset);
            if (level.TargetFrameRate > 0)
            {
                Application.targetFrameRate = level.TargetFrameRate;
            }
        }

        /// <summary>
        /// Applies the world-scoped half: streaming radii, traffic budget, sun shadows and the car's
        /// exhaust emitters.
        ///
        /// <para>Called twice, on purpose. <c>WorldStreamingDriver</c> asks for it before its own first
        /// streaming pass — that pass is deliberately immediate, "or the first few frames render every
        /// chunk in the world", and it is not ordered against <c>GameBootstrap</c>'s resumed coroutine.
        /// <c>StartScreen</c> then calls it again once everything is wired. Both are cheap and both are
        /// idempotent; relying on either one alone is relying on a race.</para>
        /// </summary>
        public void ApplyToWorld()
        {
            Level level = LevelFor(Current);
            if (string.IsNullOrEmpty(level.Name))
            {
                return;
            }

            WorldStreamer streamer = FindFirstObjectByType<WorldStreamer>();
            if (streamer != null)
            {
                streamer.SetRadii(
                    level.StreamLoadRadius, level.StreamUnloadRadius, level.StreamPhysicsMargin);
            }

            TrafficDirector traffic = FindFirstObjectByType<TrafficDirector>();
            if (traffic != null)
            {
                traffic.SetRanges(level.TrafficLoadRadius, level.TrafficRecycleRadius);
                traffic.ActiveBudget = level.TrafficBudget;
            }

            TimeOfDayController timeOfDay = FindFirstObjectByType<TimeOfDayController>();
            if (timeOfDay != null && timeOfDay.Shadows != level.SunShadows)
            {
                timeOfDay.Shadows = level.SunShadows;
                timeOfDay.Apply();
            }

            SetCameraAntialiasing(level.CameraAntialiasing);
            SetExhaustEnabled(level.ExhaustParticles);
            SetTyreSmokeEnabled(level.TyreSmokeParticles);
            SetAirRushEnabled(level.AirRushParticles);
            SetRainDrops(level.RainDrops);
            SetBloom(level.Bloom);
        }

        /// <summary>
        /// Turns the camera's FXAA on or off.
        ///
        /// <para>On the camera's <c>UniversalAdditionalCameraData</c> and not on the pipeline asset,
        /// which is the whole reason this can be a per-preset setting at all: the camera lives in a
        /// scene, so a value written to it in Play mode is discarded when Play mode ends. The asset is
        /// not, and would be left modified in the player's working tree — the hazard this class's own
        /// remarks open with.</para>
        ///
        /// <para>Found through <c>Camera.main</c> rather than cached: the rig is tagged MainCamera and
        /// is never replaced, but this runs on a settings change rather than per frame, so there is
        /// nothing to save by holding a reference the world might not have created yet.</para>
        /// </summary>
        private static void SetCameraAntialiasing(bool enabled)
        {
            Camera camera = Camera.main;
            if (camera == null)
            {
                return;
            }

            UniversalAdditionalCameraData data = camera.GetUniversalAdditionalCameraData();
            if (data == null)
            {
                return;
            }

            data.antialiasing = enabled
                ? AntialiasingMode.FastApproximateAntialiasing
                : AntialiasingMode.None;
        }

        /// <summary>
        /// Thins the rain rather than switching it off.
        ///
        /// <para>Unlike the three above, and the difference is what the effect is for. Grit, tailpipe
        /// smoke and tyre smoke are decoration: cutting them costs nothing but polish. Rain is a state
        /// the world is in — the road is slippery and there is a noise on the roof — and a phone that
        /// showed none of it while both of those were true would be telling the player something false.
        /// So Low draws a third of the drops rather than none.</para>
        /// </summary>
        private static void SetRainDrops(float scale)
        {
            WeatherDirector weather = FindFirstObjectByType<WeatherDirector>();
            if (weather != null)
            {
                weather.DropScale = scale;
            }
        }

        /// <summary>
        /// Turns the bloom volume's weight up or down.
        ///
        /// <para>Through <see cref="PostProcessing"/> rather than at a <c>Volume</c> found here, because
        /// the world scene holds two of them and nothing about the type says which is which — see that
        /// class for why the profile itself is never touched.</para>
        /// </summary>
        private static void SetBloom(float amount)
        {
            PostProcessing post = FindFirstObjectByType<PostProcessing>();
            if (post != null)
            {
                post.BloomAmount = amount;
            }
        }

        /// <summary>
        /// Switches the car's two tailpipe emitters on or off.
        ///
        /// <para>Found through the vehicle rather than cached, because the car's active body — and
        /// therefore which pair of emitters exists — changes whenever the player picks another shape.
        /// A cached reference would be to the emitters of a car nobody is driving. This runs on a
        /// settings change, not per frame, so the search costs nothing that matters.</para>
        /// </summary>
        private static void SetExhaustEnabled(bool enabled)
        {
            Vehicle.VehicleController vehicle = FindFirstObjectByType<Vehicle.VehicleController>();
            if (vehicle == null)
            {
                return;
            }

            Vehicle.ExhaustSmoke[] emitters = vehicle.GetComponentsInChildren<Vehicle.ExhaustSmoke>(true);
            for (int i = 0; i < emitters.Length; i++)
            {
                emitters[i].enabled = enabled;

                var particles = emitters[i].GetComponent<ParticleSystem>();
                if (particles == null)
                {
                    continue;
                }

                if (enabled)
                {
                    particles.Play();
                }
                else
                {
                    // Clear as well as stop, or the plume that was in the air hangs there.
                    particles.Stop(true, ParticleSystemStopBehavior.StopEmittingAndClear);
                }
            }
        }

        /// <summary>
        /// Switches the air-rush grit on or off.
        ///
        /// <para>Found through the atmosphere rather than the vehicle, because that is where it hangs —
        /// it belongs to the world, not to the car.</para>
        /// </summary>
        private static void SetAirRushEnabled(bool enabled)
        {
            SpeedAtmosphere speed = FindFirstObjectByType<SpeedAtmosphere>();
            if (speed == null)
            {
                return;
            }

            ParticleSystem[] emitters = speed.GetComponentsInChildren<ParticleSystem>(true);
            for (int i = 0; i < emitters.Length; i++)
            {
                if (enabled)
                {
                    emitters[i].Play();
                }
                else
                {
                    emitters[i].Stop(true, ParticleSystemStopBehavior.StopEmittingAndClear);
                }
            }

            speed.RushEnabled = enabled;
        }

        /// <summary>
        /// Switches the tyre smoke on or off.
        ///
        /// <para>Separate from the exhaust and searched separately, because it sits on the chassis
        /// rather than on a body — swapping cars in the garage does not replace it, but the same
        /// find-through-the-vehicle rule is kept so there is one way this is done rather than two.</para>
        ///
        /// <para>Disabling the component is not enough on its own: it stops new puffs, but a cloud
        /// already lying on the road would sit there until it aged out.</para>
        /// </summary>
        private static void SetTyreSmokeEnabled(bool enabled)
        {
            Vehicle.VehicleController vehicle = FindFirstObjectByType<Vehicle.VehicleController>();
            if (vehicle == null)
            {
                return;
            }

            Vehicle.TyreSmoke[] emitters = vehicle.GetComponentsInChildren<Vehicle.TyreSmoke>(true);
            for (int i = 0; i < emitters.Length; i++)
            {
                emitters[i].enabled = enabled;

                var particles = emitters[i].GetComponent<ParticleSystem>();
                if (particles == null)
                {
                    continue;
                }

                if (enabled)
                {
                    particles.Play();
                }
                else
                {
                    particles.Stop(true, ParticleSystemStopBehavior.StopEmittingAndClear);
                }
            }
        }
    }
}
