using Horizon.Atmosphere;
using Horizon.World;
using UnityEngine;

namespace Horizon.Game
{
    /// <summary>
    /// How much world to draw, in three settings.
    ///
    /// <para><b>What this deliberately does not touch: the URP assets.</b>
    /// <c>Assets/Settings/Mobile_RPAsset.asset</c> holds the render scale, the MSAA count and the shadow
    /// distance, and it would be the obvious place to put a quality slider. It is also not generated by
    /// <c>PrototypeSetup</c>, and Unity does <b>not</b> roll asset changes back when Play mode ends — so
    /// a player who tried Low once would leave that file modified in the working tree, which is the same
    /// hazard <c>TownLights</c> documents for materials. <c>QualitySettings.SetQualityLevel</c> is no way
    /// round it either: there are exactly two levels, Mobile and PC, each excluded from the other's
    /// platform. Everything here is therefore a runtime value on a component.</para>
    ///
    /// <para>Worth knowing while reading this: URP ignores <c>QualitySettings.shadowDistance</c> and
    /// <c>shadowCascades</c> entirely — it has its own — so setting them would look like it worked and
    /// do nothing. Shadows are switched at the source instead, through
    /// <see cref="TimeOfDayController.Shadows"/>.</para>
    ///
    /// <para><b>Two phases, because the world arrives late.</b> <see cref="Apply"/> handles what is
    /// global and can be set before anything exists — the frame rate. <see cref="ApplyToWorld"/> handles
    /// the streamer, the traffic and the sun, and can only run once the additive load has finished.</para>
    /// </summary>
    public sealed class QualityDirector : MonoBehaviour
    {
        /// <summary>One setting, as the numbers it actually moves.</summary>
        [System.Serializable]
        public struct Level
        {
            public string Name;

            [Header("World streaming")]
            public float StreamLoadRadius;
            public float StreamUnloadRadius;
            public float StreamPhysicsMargin;

            [Header("Traffic")]
            [Tooltip("How many of the 96 pooled cars are simulated and drawn.")]
            public int TrafficBudget;

            public float TrafficLoadRadius;
            public float TrafficRecycleRadius;

            [Header("Rendering")]
            public bool SunShadows;

            [Tooltip("Exhaust smoke and flames. Two particle systems on the active body.")]
            public bool ExhaustParticles;

            [Tooltip("Smoke off the tyres when they slide.\n\n"
                   + "Kept apart from the exhaust rather than folded in with it, because the two cost "
                   + "very different things. The tailpipes trickle at a fixed low rate all the time; "
                   + "this one is idle for most of a drive and then asks for its whole budget at once, "
                   + "during a slide — which is also the frame that is already doing the most work.")]
            public bool TyreSmokeParticles;

            [Tooltip("The grit hanging in the air at speed.\n\n"
                   + "The first thing to go on a weak phone, and the easiest call of the three: it is "
                   + "pure atmosphere, it is only ever on show while the player is going fast, and the "
                   + "fog closing in — which costs nothing at all — carries the same message without it.")]
            public bool AirRushParticles;

            [Tooltip("How many raindrops of the full count to draw, 0 to 1.\n\n"
                   + "A fraction rather than a switch, because rain is the one weather effect that has "
                   + "to be visible at all if it is chosen at all — a Low phone showing no rain while "
                   + "the sound falls and the road is slippery is a bug, not a saving. The sky, the "
                   + "noise and the grip never scale with this; only the drop count does.")]
            public float RainDrops;

            [Tooltip("30 on Low is a real thermal and battery win on a weak phone, and a steady 30 "
                   + "reads better than a 60 that cannot hold.")]
            public int TargetFrameRate;
        }

        [SerializeField] private Level[] levels = new Level[0];

        /// <summary>The setting currently applied.</summary>
        public QualityPreset Current { get; private set; } = QualityPreset.Balanced;

        /// <summary>The level record for a preset, clamped to what was actually baked.</summary>
        public Level LevelFor(QualityPreset preset)
        {
            if (levels == null || levels.Length == 0)
            {
                return default;
            }

            return levels[Mathf.Clamp((int)preset, 0, levels.Length - 1)];
        }

        /// <summary>
        /// Applies what can be set before the world exists. Called from <c>GameBootstrap.Awake</c>,
        /// which is the last moment before the additive load starts.
        /// </summary>
        public void Apply(QualityPreset preset)
        {
            Current = preset;

            Level level = LevelFor(preset);
            if (level.TargetFrameRate > 0)
            {
                Application.targetFrameRate = level.TargetFrameRate;
            }
        }

        /// <summary>
        /// Applies the world-scoped half: streaming radii, traffic budget, sun shadows and the car's
        /// exhaust emitters.
        ///
        /// <para>Called twice, on purpose. <c>WorldStreamingDriver</c> asks for it before its own first
        /// streaming pass — that pass is deliberately immediate, "or the first few frames render every
        /// chunk in the world", and it is not ordered against <c>GameBootstrap</c>'s resumed coroutine.
        /// <c>StartScreen</c> then calls it again once everything is wired. Both are cheap and both are
        /// idempotent; relying on either one alone is relying on a race.</para>
        /// </summary>
        public void ApplyToWorld()
        {
            Level level = LevelFor(Current);
            if (string.IsNullOrEmpty(level.Name))
            {
                return;
            }

            WorldStreamer streamer = FindFirstObjectByType<WorldStreamer>();
            if (streamer != null)
            {
                streamer.SetRadii(
                    level.StreamLoadRadius, level.StreamUnloadRadius, level.StreamPhysicsMargin);
            }

            TrafficDirector traffic = FindFirstObjectByType<TrafficDirector>();
            if (traffic != null)
            {
                traffic.SetRanges(level.TrafficLoadRadius, level.TrafficRecycleRadius);
                traffic.ActiveBudget = level.TrafficBudget;
            }

            TimeOfDayController timeOfDay = FindFirstObjectByType<TimeOfDayController>();
            if (timeOfDay != null && timeOfDay.Shadows != level.SunShadows)
            {
                timeOfDay.Shadows = level.SunShadows;
                timeOfDay.Apply();
            }

            SetExhaustEnabled(level.ExhaustParticles);
            SetTyreSmokeEnabled(level.TyreSmokeParticles);
            SetAirRushEnabled(level.AirRushParticles);
            SetRainDrops(level.RainDrops);
        }

        /// <summary>
        /// Thins the rain rather than switching it off.
        ///
        /// <para>Unlike the three above, and the difference is what the effect is for. Grit, tailpipe
        /// smoke and tyre smoke are decoration: cutting them costs nothing but polish. Rain is a state
        /// the world is in — the road is slippery and there is a noise on the roof — and a phone that
        /// showed none of it while both of those were true would be telling the player something false.
        /// So Low draws a third of the drops rather than none.</para>
        /// </summary>
        private static void SetRainDrops(float scale)
        {
            WeatherDirector weather = FindFirstObjectByType<WeatherDirector>();
            if (weather != null)
            {
                weather.DropScale = scale;
            }
        }

        /// <summary>
        /// Switches the car's two tailpipe emitters on or off.
        ///
        /// <para>Found through the vehicle rather than cached, because the car's active body — and
        /// therefore which pair of emitters exists — changes whenever the player picks another shape.
        /// A cached reference would be to the emitters of a car nobody is driving. This runs on a
        /// settings change, not per frame, so the search costs nothing that matters.</para>
        /// </summary>
        private static void SetExhaustEnabled(bool enabled)
        {
            Vehicle.VehicleController vehicle = FindFirstObjectByType<Vehicle.VehicleController>();
            if (vehicle == null)
            {
                return;
            }

            Vehicle.ExhaustSmoke[] emitters = vehicle.GetComponentsInChildren<Vehicle.ExhaustSmoke>(true);
            for (int i = 0; i < emitters.Length; i++)
            {
                emitters[i].enabled = enabled;

                var particles = emitters[i].GetComponent<ParticleSystem>();
                if (particles == null)
                {
                    continue;
                }

                if (enabled)
                {
                    particles.Play();
                }
                else
                {
                    // Clear as well as stop, or the plume that was in the air hangs there.
                    particles.Stop(true, ParticleSystemStopBehavior.StopEmittingAndClear);
                }
            }
        }

        /// <summary>
        /// Switches the air-rush grit on or off.
        ///
        /// <para>Found through the atmosphere rather than the vehicle, because that is where it hangs —
        /// it belongs to the world, not to the car.</para>
        /// </summary>
        private static void SetAirRushEnabled(bool enabled)
        {
            SpeedAtmosphere speed = FindFirstObjectByType<SpeedAtmosphere>();
            if (speed == null)
            {
                return;
            }

            ParticleSystem[] emitters = speed.GetComponentsInChildren<ParticleSystem>(true);
            for (int i = 0; i < emitters.Length; i++)
            {
                if (enabled)
                {
                    emitters[i].Play();
                }
                else
                {
                    emitters[i].Stop(true, ParticleSystemStopBehavior.StopEmittingAndClear);
                }
            }

            speed.RushEnabled = enabled;
        }

        /// <summary>
        /// Switches the tyre smoke on or off.
        ///
        /// <para>Separate from the exhaust and searched separately, because it sits on the chassis
        /// rather than on a body — swapping cars in the garage does not replace it, but the same
        /// find-through-the-vehicle rule is kept so there is one way this is done rather than two.</para>
        ///
        /// <para>Disabling the component is not enough on its own: it stops new puffs, but a cloud
        /// already lying on the road would sit there until it aged out.</para>
        /// </summary>
        private static void SetTyreSmokeEnabled(bool enabled)
        {
            Vehicle.VehicleController vehicle = FindFirstObjectByType<Vehicle.VehicleController>();
            if (vehicle == null)
            {
                return;
            }

            Vehicle.TyreSmoke[] emitters = vehicle.GetComponentsInChildren<Vehicle.TyreSmoke>(true);
            for (int i = 0; i < emitters.Length; i++)
            {
                emitters[i].enabled = enabled;

                var particles = emitters[i].GetComponent<ParticleSystem>();
                if (particles == null)
                {
                    continue;
                }

                if (enabled)
                {
                    particles.Play();
                }
                else
                {
                    particles.Stop(true, ParticleSystemStopBehavior.StopEmittingAndClear);
                }
            }
        }
    }
}
